---
title: "Airline Route Profitability"
output: html_document
date: "2026-04-16"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(tidyr)
```

```{r}
#Loading Data
airline_data <- read_csv("airline_route_profitability.csv")
glimpse(airline_data)
```

```{r}
head(airline_data)
```

```{r}
#Missing value check
colSums(is.na(airline_data))
airline_clean <- airline_data %>%
  mutate(across(where(is.numeric),
                ~ifelse(is.na(.), median(., na.rm = TRUE), .)))

```
```{r}
glimpse(airline_clean)
```

```{r}
#Average profit by season
airline_clean %>%
  group_by(Season) %>%
  summarize(avg_profit = mean(Profit, na.rm = TRUE))
# Low - slowest travel period
#Normal - regular travel period
#Peak - Not super busy, not super quiet, more than Normal.
#Shoulder - busiest travel period
```

```{r}
# Average profit by route category
airline_clean %>%
  group_by(Route_Category) %>%
  summarize(avg_profit = mean(Profit, na.rm = TRUE))

#Short Haul = 1 to 3.5 hours
#Medium Haul = 2.5 to 7 hours
#Long Haul = 6.5 to 16.5 hours
```


```{r}
#Average profit by demand level
airline_clean %>%
  group_by(Demand_Level) %>%
  summarize(avg_profit = mean(Profit, na.rm = TRUE))
```

```{r}
#Flight count by season
ggplot(data = airline_clean, aes(x = Season)) +
  geom_bar() +
  labs(
    title = "Number of Flight Observations by Season",
    x = "Season",
    y = "Number of Flights"
  )

```
Low - slowest travel period
Normal - regular travel period
Peak - Not super busy, not super quiet, more than Normal.
Shoulder - busiest travel period

```{r}
#How profit spreads out across flights?

ggplot(airline_clean, aes(x = Profit)) +
  geom_histogram(binwidth = 50000) +
  labs(
    title = "Distribution of Profit",
    x = "Profit (USD)",
    y = "Number of Flights"
  )
```
x-axis values are in dollars. 0e+00 = $0, 5e+05 = $500,000, 1e+06 = $1,000,000

```{r}
#Profit by Route Category
ggplot(airline_clean, aes(x = Route_Category, y = Profit)) +
  geom_boxplot() +
  labs(
    title = "Profit by Route Category",
    x = "Route Category",
    y = "Profit (USD)"
  )
```

```{r}
#Load Factor VS Profit
ggplot(airline_clean, aes(x = Load_Factor, y = Profit)) +
  geom_point(alpha = 1/3) +
  labs(
    title = "Load Factor vs Profit",
    x = "Load Factor",
    y = "Profit (USD)"
  )
#Load_Factor = Passengers/Aircraft Capacity
```

